#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export DBMAN_NAME=''dbman'';
export DBMAN_CODE=''dbman'';

export DBMAN_VERSION='0.1.3';
export DBMAN_VERSION_MAJOR='0';
export DBMAN_VERSION_MINOR='1';
export DBMAN_VERSION_PATCH='3';

export DBMAN_SVN_DATE='Date: 2024-10-21 07:50:42 +1100 (Mon, 21 Oct 2024)';
export DBMAN_SVN_REVISION='Revision: 246211975';
export DBMAN_SVN_AUTHOR='Author: jj5';

export DBMAN_GIT_DATE='2024-10-21 07:50:42 +1100 (Mon, 21 Oct 2024)';
